databases:
  - name: kanban-postgres
    databaseName: kanban
    user: kanban_user
    plan: free

services:
  # API Gateway
  - type: web
    name: kanban-api-gateway
    env: node
    plan: free
    buildCommand: cd backend/services/api-gateway && npm install --include=dev && npm run build
    startCommand: cd backend/services/api-gateway && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CORS_ORIGIN
        value: "*"

  # Auth Service
  - type: web
    name: kanban-auth-service
    env: node
    plan: free
    buildCommand: cd backend/services/auth-service && npm install --include=dev && npm run build
    startCommand: cd backend/services/auth-service && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CORS_ORIGIN
        value: "*"
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES_IN
        value: "15m"
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"

  # User Service
  - type: web
    name: kanban-user-service
    env: node
    plan: free
    buildCommand: cd backend/services/user-service && npm install --include=dev && npm run build
    startCommand: cd backend/services/user-service && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: "*"

  # Board Service
  - type: web
    name: kanban-board-service
    env: node
    plan: free
    buildCommand: cd backend/services/board-service && npm install --include=dev && npm run build
    startCommand: cd backend/services/board-service && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: "*"

  # List Service
  - type: web
    name: kanban-list-service
    env: node
    plan: free
    buildCommand: cd backend/services/list-service && npm install --include=dev && npm run build
    startCommand: cd backend/services/list-service && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3004
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: "*"

  # Card Service
  - type: web
    name: kanban-card-service
    env: node
    plan: free
    buildCommand: cd backend/services/card-service && npm install --include=dev && npm run build
    startCommand: cd backend/services/card-service && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3005
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: "*"

  # Notification Service
  - type: web
    name: kanban-notification-service
    env: node
    plan: free
    buildCommand: cd backend/services/notification-service && npm install --include=dev && npm run build
    startCommand: cd backend/services/notification-service && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3006
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CORS_ORIGIN
        value: "*"

  # File Service
  - type: web
    name: kanban-file-service
    env: node
    plan: free
    buildCommand: cd backend/services/file-service && npm install --include=dev && npm run build
    startCommand: cd backend/services/file-service && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3007
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: CORS_ORIGIN
        value: "*" 