databases:
  - name: kanban-postgres
    databaseName: kanban
    user: kanban_user
    plan: free

services:
  # API Gateway
  - type: web
    name: kanban-api-gateway
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build:gateway
    startCommand: cd backend/services/api-gateway && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CORS_ORIGIN
        value: "*"

  # Auth Service
  - type: web
    name: kanban-auth-service
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build:auth
    startCommand: cd backend/services/auth-service && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CORS_ORIGIN
        value: "*"

  # User Service
  - type: web
    name: kanban-user-service
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build:user
    startCommand: cd backend/services/user-service && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: "*"

  # Board Service
  - type: web
    name: kanban-board-service
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build:board
    startCommand: cd backend/services/board-service && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: "*"

  # List Service
  - type: web
    name: kanban-list-service
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build:list
    startCommand: cd backend/services/list-service && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3004
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: "*"

  # Card Service
  - type: web
    name: kanban-card-service
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build:card
    startCommand: cd backend/services/card-service && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3005
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: "*"

  # Notification Service
  - type: web
    name: kanban-notification-service
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build:notification
    startCommand: cd backend/services/notification-service && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3006
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CORS_ORIGIN
        value: "*"

  # File Service
  - type: web
    name: kanban-file-service
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build:file
    startCommand: cd backend/services/file-service && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3007
      - key: DATABASE_URL
        fromDatabase:
          name: kanban-postgres
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: CORS_ORIGIN
        value: "*" 